pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo "Pulling code from GitHub..."
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo "Installing Python dependencies..."
                sh """
                    pip install -r requirements.txt
                """
            }
        }

        stage('Docker Build') {
            steps {
                echo "Building Docker image..."
                sh """
                    docker build -t tripti-devops-app .
                """
            }
        }

        stage('Run Container') {
            steps {
                echo "Running container..."
                sh """
                    docker run -d -p 5000:5000 --name tripti-app tripti-devops-app
                """
            }
        }

        stage('Post-Build Cleanup') {
            steps {
                echo "Cleaning existing container if needed..."
                sh "docker ps -a"
            }
        }
    }

    post {
        always {
            echo "Pipeline finished!"
        }
    }
}
