pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/TriptiP-Code/tripti-devops-project.git', branch: 'main'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat '''
                echo Installing dependencies...
                REM If needed, install requirements here
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                bat '''
                echo Building Docker image...
                docker build -t tripti-app ./Project-1
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                bat '''
                echo Running Docker container...
                docker run -d -p 5000:5000 --name tripti-container tripti-app
                '''
            }
        }
    }
}
